# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57da80ffab94fac41025a65994f06397398c323542fbabff627431c7e5e0d90d5b05a1a00081b9f88ee0e520e5dc253ede54f71daa30fbc3338b809743722587

test:
  secret_key_base: 056307340f1cb1e73e8593297ff5914a97d40f0d4acb43a9cb44e90aeb20b1562fc14b937d176f00c69578762547cc7e09636b125e6d785df9d19118524b2831

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
